$content = Get-Content 'src/views/threejs/map.vue' -Raw -Encoding utf8
$bytes = [System.Text.Encoding]::GetEncoding('GBK').GetBytes($content)
$fixed = [System.Text.Encoding]::UTF8.GetString($bytes)
$fixed = $fixed.Replace("$([char]0xFFFD)", '')
$replacements = @(
  @('<!-- 标题-->', '<!-- 标题栏 -->'),
  @('<StatCard title="接种单位总数" :value="1102" unit=" position="left" />', '<StatCard title="接种单位总数" :value="1102" unit="家" position="left" />'),
  @('<StatCard title="平均完成 :value="92.34" unit="%" position="right" :decimals="2" />', '<StatCard title="平均完成率" :value="92.34" unit="%" position="right" :decimals="2" />'),
  @('<!-- ECharts 玫瑰图组-->', '<!-- ECharts 玫瑰图组件 -->'),
  @('<!-- ECharts 柱状图组-->', '<!-- ECharts 柱状图组件 -->'),
  @('<!-- 趋势折线-->', '<!-- 趋势折线图 -->'),
  @('// 导入 ECharts 玫瑰图组', '// 导入 ECharts 玫瑰图组件'),
  @('// 导入 ECharts 柱状图组', '// 导入 ECharts 柱状图组件'),
  @('let provinceLabels = new Map() // 存储所有省份标', 'let provinceLabels = new Map() // 存储所有省份标签'),
  @('let mapGroup = null // 地图组（供射线检测用', 'let mapGroup = null // 地图组（供射线检测用）'),
  @('// 视角状态：初始为远景（正俯视江苏居中），切换后为近', '// 视角状态：初始为远景（正俯视江苏居中），切换后为近景'),
  @('// 粒子特效状态显', '// 粒子特效状态显示'),
  @("const isJiangsu = name === '江苏'", "const isJiangsu = name === '江苏省'"),
  @('// 逻辑画布尺寸（CSS像素', '// 逻辑画布尺寸（CSS像素）'),
  @('// 背景（半透明圆角', '// 背景（半透明圆角）'),
  @('// 主文字绘制在画布上半部分（使用逻辑像素', '// 主文字绘制在画布上半部分（使用逻辑像素）'),
  @('// （主画布只绘制主文字，反射单独用反射画布绘制，以便用不同透明/渐隐', '// （主画布只绘制主文字，反射单独用反射画布绘制，以便用不同透明/渐隐）'),
  @('// 2. 创建纹理和精灵材', '// 2. 创建纹理和精灵材质'),
  @('// 使用线性过滤并关闭mipmap（画布纹理通常不需要mipmap', '// 使用线性过滤并关闭 mipmap（画布纹理通常不需要 mipmap）'),
  @('depthWrite: false, // 不写入深', 'depthWrite: false, // 不写入深度'),
  @('// 3. 创建显示对象：江苏使用Plane Mesh（主+ 倒影），其它省份仍使用Sprite', '// 3. 创建显示对象：江苏使用 Plane Mesh（主字 + 倒影），其它省份仍使用 Sprite'),
  @('// ===== 江苏：使用两块平面（+ 倒影=====','// ===== 江苏：使用两块平面（主字 + 倒影） ====='),
  @('// 渐隐遮罩（从上到下透明', '// 渐隐遮罩（从上到下透明）'),
  @('// 竖向翻转反射，使倒影呈镜像状', '// 竖向翻转反射，使倒影呈镜像状态'),
  @('// 更新反射画布（保持文字正常方向，使用较低透明度并渐隐', '// 更新反射画布（保持文字正常方向，使用较低透明度并渐隐）'),
  @('// 创建市文字标', '// 创建市文字标签'),
  @('// 设置文字样式 - 带发光效', '// 设置文字样式 - 带发光效果'),
  @("// ctx.shadowColor = '#69e2f2'  // 发光颜色(蓝绿", "// ctx.shadowColor = '#69e2f2'  // 发光颜色（蓝绿色）"),
  @('// ctx.shadowBlur = 1 // 发光模糊', '// ctx.shadowBlur = 1 // 发光模糊度'),
  @('// 创建纹理和材', '// 创建纹理和材质'),
  @('// ===== 替换原柱状图代码：创建“发光科技柱=====','// ===== 替换原柱状图代码：创建“发光科技柱” ====='),
  @('ctx.fillText(`${cityData.total}`', 'ctx.fillText(`${cityData.total}家`'),
  @('ctx.fillText(`ռȫʡ ${share}%`, panelX + 16, panelY + 80)', 'ctx.fillText(`占全省 ${share}%`, panelX + 16, panelY + 80)'),
  @('const barRadius = 0.1 // 柱体半径（对应CylinderGeometry的顶部半径', 'const barRadius = 0.1 // 柱体半径（对应 CylinderGeometry 的顶部/底部半径）'),
  @('// 用MeshBasicMaterial+顶点颜色实现渐变（底部暗、顶部亮', '// 用 MeshBasicMaterial + 顶点颜色实现渐变（底部暗、顶部亮）'),
  @('const ratio = (y + height / 2) / height // 0~1（底部到顶部', 'const ratio = (y + height / 2) / height // 0~1（底部到顶部）'),
  @('// 计算GeoJSON特征的几何中心（兼容MultiPolygon/Polygon', '// 计算 GeoJSON 特征的几何中心（兼容 MultiPolygon/Polygon）'),
  @('// 江苏市级数据3市边界）', '// 江苏市级数据（13 市边界）'),
  @('// 2. 清除旧地创建地图', '// 2. 清除旧地图，创建地图组'),
  @('// 3. 关键：D3投影配置（完整中江苏居中', '// 3. 关键：D3 投影配置（完整中国，江苏居中）'),
  @('.translate([2, 0]) // 平移到原', '.translate([2, 0]) // 平移到原点'),
  @('// 定义样式常量（科技蓝明亮风', '// 定义样式常量（科技蓝明亮风格）'),
  @('// 其他省份样式（基础暗蓝', '// 其他省份样式（基础暗蓝）'),
  @('// 江苏省突出样式（科技加高', '// 江苏省突出样式（科技感 + 加高）'),
  @('// highlightColor: 0x47E5FF,// 高光', '// highlightColor: 0x47E5FF, // 高光色'),
  @('// 提取GeoJSON中的经纬度坐标（多面/单面对象兼容', '// 提取 GeoJSON 中的经纬度坐标（多面/单面对象兼容）'),
  @('// 经纬度转Three.js坐标（用D3投影', '// 经纬度转 Three.js 坐标（用 D3 投影）'),
  @('return new THREE.Vector2(x, y) // D Vector', 'return new THREE.Vector2(x, y) // 2D Vector'),
  @('// 其他省份：基础平面几何', '// 其他省份：基础平面几何体'),
  @('// 旋转适配坐标系（保持平躺', '// 旋转适配坐标系（保持平躺）'),
  @('// 材质配置（科技蓝明亮风', '// 材质配置（科技蓝明亮风格）'),
  @('// shininess: 80,                          // 光泽度（明亮', '// shininess: 80,                          // 光泽度（明亮）'),
  @('// 创建Mesh并设置位', '// 创建 Mesh 并设置位置'),
  @('// 6.渲染江苏13市边', '// 6. 渲染江苏 13 市边界'),
  @('// 修复1：统一坐标结构（不管MultiPolygon/Polygon', '// 修复1：统一坐标结构（不管 MultiPolygon/Polygon）'),
  @('// 计算市级中心（用于放置柱状图', '// 计算市级中心（用于放置柱状图）'),
  @('// 修复3：解析坐标时加类型校验，避免解构单个数', '// 修复3：解析坐标时加类型校验，避免解构单个数值'),
  @('.filter((p) => p !== null) // 过滤无效', '.filter((p) => p !== null) // 过滤无效点'),
  @('// 创建市级面并保存cityMeshes（防止遮挡柱子，设置半透明', '// 创建市级面并保存到 cityMeshes（防止遮挡柱子，设置半透明）'),
  @('// 保存（可能一个城市有多块', '// 保存（可能一个城市有多块）'),
  @('// 恢复上一', '// 恢复上一个'),
  @('mesh.material.color.set(0xa6cde6) // 高亮色，可自行调', 'mesh.material.color.set(0xa6cde6) // 高亮色，可自行调整'),
  @('// 初始设置为远景：正俯视江苏中', '// 初始设置为远景：正俯视江苏中心'),
  @('// 3.创建渲染', '// 3.创建渲染器'),
  @('// 4.添加控制', '// 4.添加控制器'),
  @('// 调整大小更合', '// 调整大小更合适'),
  @('// 确保透明', '// 确保透明度'),
  @('// 反方向旋', '// 反方向旋转'),
  @("//   const lightFolder = gui.addFolder('AmbientLight环境", "//   const lightFolder = gui.addFolder('AmbientLight环境光')"),
  @("//     .name('环境光颜", "//     .name('环境光颜色')"),
  @("//   lightFolder.add(lightParams, 'intensity', 0, 1, 0.1).name('环境光强", "//   lightFolder.add(lightParams, 'intensity', 0, 1, 0.1).name('环境光强度')"),
  @('//   // 直射', '//   // 直射光'),
  @("//   const dirLightFolder = gui.addFolder('DirectionalLight直射", "//   const dirLightFolder = gui.addFolder('DirectionalLight直射光')"),
  @("//     .name('直射光颜", "//     .name('直射光颜色')"),
  @("//   dirLightFolder.add(lightParams2, 'intensity', 0, 1, 0.1).name('直射光强", "//   dirLightFolder.add(lightParams2, 'intensity', 0, 1, 0.1).name('直射光强度')"),
  @("//   dirLightFolder.add(lightParams2, 'x', -10, 10, 1).name('直射光x轴位", "//   dirLightFolder.add(lightParams2, 'x', -10, 10, 1).name('直射光x轴位置')"),
  @('//       // 1. 收集原始经纬度转换的坐标（x对应经度，z对应纬度，y', '//       // 1. 收集原始经纬度转换的坐标（x 对应经度，z 对应纬度，y 为 0）'),
  @('//         flatPoints.push(new THREE.Vector3(x, 0, z)); // y=0，保持平', '//         flatPoints.push(new THREE.Vector3(x, 0, z)); // y=0，保持平面'),
  @('//       // 3. 线框：基于旋转后的平面坐标，仅在y方向抬高0.01（贴近填充面', '//       // 3. 线框：基于旋转后的平面坐标，仅在 y 方向抬高 0.01（贴近填充面）'),
  @('//         // 旋转后，原z轴映射到视觉上的"y方向"，需转换为旋转后的平面坐', '//         // 旋转后，原 z 轴映射到视觉上的 "y 方向"，需转换为旋转后的平面坐标'),
  @('//         return new THREE.Vector3(p.x, 0.2 + 0.01, -p.z); // -p.z抵消旋转带来的方向反', '//         return new THREE.Vector3(p.x, 0.2 + 0.01, -p.z); // -p.z 抵消旋转带来的方向反转'),
  @('// ===== 新增：鼠标悬浮交互（使用外层的mapGroup和provinceLabels====', '// ===== 新增：鼠标悬浮交互（使用外层的 mapGroup 和 provinceLabels）====='),
  @('// 若地图组还没加载，直接返', '// 若地图组还没加载，直接返回'),
  @('// 检测地图组内的Mesh（过滤非Mesh对象，比如Line、Sprite', '// 检测地图组内的 Mesh（过滤非 Mesh 对象，比如 Line、Sprite）'),
  @('// 清除上一个悬浮状', '// 清除上一个悬浮状态'),
  @('// 点击处理：优先检cityMeshes 中的 Mesh', '// 点击处理：优先检测 cityMeshes 中的 Mesh'),
  @('// 组件卸载时移除事', '// 组件卸载时移除事件'),
  @('// 卸载时清理飞线资', '// 卸载时清理飞线资源'),
  @('// 让使用Plane 的标签始终面向相机（例如江苏省）', '// 让使用 Plane 的标签始终面向相机（例如江苏省）'),
  @("  { city: '南京市', unit: '鼓楼区接种中', rate: 84.3, delta: -2.4, statusText: '预警', statusClass: 'warning' },", "  { city: '南京市', unit: '鼓楼区接种中心', rate: 84.3, delta: -2.4, statusText: '预警', statusClass: 'warning' },"),
  @("  { city: '无锡市', unit: '梁溪区妇幼保健院', rate: 88.5, delta: -0.9, statusText: '待跟', statusClass: 'follow' },", "  { city: '无锡市', unit: '梁溪区妇幼保健院', rate: 88.5, delta: -0.9, statusText: '待跟进', statusClass: 'follow' },"),
  @("  { city: '常州市', unit: '新北区公共卫生中', rate: 90.8, delta: 0.6, statusText: '待跟', statusClass: 'follow' },", "  { city: '常州市', unit: '新北区公共卫生中心', rate: 90.8, delta: 0.6, statusText: '待跟进', statusClass: 'follow' },"),
  @("  { city: '南通市', unit: '崇川区社区卫生中', rate: 92.4, delta: 1.2, statusText: '正常', statusClass: 'normal' },", "  { city: '南通市', unit: '崇川区社区卫生中心', rate: 92.4, delta: 1.2, statusText: '正常', statusClass: 'normal' },"),
  @("  { city: '盐城市', unit: '亭湖区预防接种门', rate: 87.3, delta: -1.1, statusText: '待跟', statusClass: 'follow' },", "  { city: '盐城市', unit: '亭湖区预防接种门诊', rate: 87.3, delta: -1.1, statusText: '待跟进', statusClass: 'follow' },"),
  @("  { city: '泰州市', unit: '海陵区疾控中', rate: 89.1, delta: -0.4, statusText: '待跟', statusClass: 'follow' },", "  { city: '泰州市', unit: '海陵区疾控中心', rate: 89.1, delta: -0.4, statusText: '待跟进', statusClass: 'follow' },"),
  @("  { city: '宿迁市', unit: '宿城区接种门', rate: 85.2, delta: -2.2, statusText: '预警', statusClass: 'warning' },", "  { city: '宿迁市', unit: '宿城区接种门诊', rate: 85.2, delta: -2.2, statusText: '预警', statusClass: 'warning' },"),
  @("  { city: '镇江市', unit: '京口区社区卫生院', rate: 90.2, delta: 0.3, statusText: '待跟', statusClass: 'follow' },", "  { city: '镇江市', unit: '京口区社区卫生院', rate: 90.2, delta: 0.3, statusText: '待跟进', statusClass: 'follow' },"),
  @("  { city: '连云港市', unit: '海州区接种中', rate: 82.9, delta: -2.8, statusText: '预警', statusClass: 'warning' },", "  { city: '连云港市', unit: '海州区接种中心', rate: 82.9, delta: -2.8, statusText: '预警', statusClass: 'warning' },"),
  @("  { city: '淮安市', unit: '淮阴区接种中', rate: 86.5, delta: -0.5, statusText: '待跟', statusClass: 'follow' }", "  { city: '淮安市', unit: '淮阴区接种中心', rate: 86.5, delta: -0.5, statusText: '待跟进', statusClass: 'follow' }"),
  @("  { name: '南京', total: 186, completed: 178, rate: 95.7 },", "  { name: '南京市', total: 186, completed: 178, rate: 95.7 },"),
  @("  { name: '苏州', total: 152, completed: 142, rate: 93.4 },", "  { name: '苏州市', total: 152, completed: 142, rate: 93.4 },"),
  @("  { name: '无锡', total: 128, completed: 118, rate: 92.2 },", "  { name: '无锡市', total: 128, completed: 118, rate: 92.2 },"),
  @("  { name: '常州', total: 95, completed: 88, rate: 92.6 },", "  { name: '常州市', total: 95, completed: 88, rate: 92.6 },"),
  @("  { name: '徐州', total: 76, completed: 68, rate: 89.5 },", "  { name: '徐州市', total: 76, completed: 68, rate: 89.5 },"),
  @("  { name: '扬州', total: 65, completed: 62, rate: 95.4 },", "  { name: '扬州市', total: 65, completed: 62, rate: 95.4 },"),
  @("  { name: '盐城', total: 58, completed: 52, rate: 89.7 },", "  { name: '盐城市', total: 58, completed: 52, rate: 89.7 },"),
  @("  { name: '泰州', total: 52, completed: 48, rate: 92.3 },", "  { name: '泰州市', total: 52, completed: 48, rate: 92.3 },"),
  @("  { name: '镇江', total: 45, completed: 44, rate: 97.8 },", "  { name: '镇江市', total: 45, completed: 44, rate: 97.8 },"),
  @("  { name: '淮安', total: 42, completed: 38, rate: 90.5 },", "  { name: '淮安市', total: 42, completed: 38, rate: 90.5 },"),
  @("  { name: '宿迁', total: 32, completed: 28, rate: 87.5 },", "  { name: '宿迁市', total: 32, completed: 28, rate: 87.5 },")
)
foreach ($pair in $replacements) { $fixed = $fixed.Replace($pair[0], $pair[1]) }
Set-Content '.codex_map_fix.ps1.out' -Value $fixed -Encoding utf8
($fixed -split "`n") | Select-String '�|ռȫʡ|��|title="平均完成|unit=" ' | ForEach-Object { $_.LineNumber.ToString() + ': ' + $_.Line }

